version: '3'

services:

  scheduler:
    restart: always
    build: .
    environment:
      - PROVIDER_URL
      - SCHEDULER_ADDRESS
      - CALENDAR_ID
      - OWNER_NAME
      - OWNER_EMAIL
      - NODE_ENV
    volumes:
      - ./credentials.json:/usr/src/app/credentials.json

    